/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.rsatarea;
import com.mycompany.rsatarea.GenerarLLaves;
import java.math.BigInteger;

/**
 *
 * @author Aaron
 */
public class Descifrar extends javax.swing.JPanel {

    private String descifrar(BigInteger[] cifrado, BigInteger d, BigInteger n){
        
        BigInteger[] descifrado = new BigInteger[cifrado.length];
        
        //vamos a descifrar con la formula
        // Md = C ^d mod n
        
        for(int j = 0; j < descifrado.length; j++){
            descifrado[j] = cifrado[j].modPow(d, n);
        }
        
        char[] charArray = new char[descifrado.length];
        
        for(int j = 0; j < charArray.length; j++ ){
            charArray[j] = (char)(descifrado[j].intValue());
        }
        
        return (new String(charArray));
    }
    
    /**
     * Creates new form Descifrar
     */
    public Descifrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textoCifrado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textoDescifrado = new javax.swing.JTextField();
        btn_descifrar = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setText("Texto cifrado:");

        textoCifrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoCifradoActionPerformed(evt);
            }
        });

        jLabel2.setText("Texto descifrado:");

        textoDescifrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoDescifradoActionPerformed(evt);
            }
        });

        btn_descifrar.setText("Descifrar");
        btn_descifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_descifrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoCifrado, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_descifrar)
                            .addComponent(textoDescifrado))))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textoCifrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textoDescifrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(btn_descifrar)
                .addGap(63, 63, 63))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textoCifradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoCifradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoCifradoActionPerformed

    private void textoDescifradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoDescifradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoDescifradoActionPerformed

    private void btn_descifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_descifrarActionPerformed
        try{
        String [] numeros = textoCifrado.getText().split(",");
        BigInteger[] cifrado = new BigInteger[numeros.length];
        for(int i=0;i<numeros.length;i++){
            System.out.println(numeros[i]);
            cifrado[i] = new BigInteger(numeros[i]);
        }
        textoDescifrado.setEditable(false);
        textoDescifrado.setText(descifrar(cifrado,GenerarLLaves.D,GenerarLLaves.N));
        }catch(Exception e){
            textoDescifrado.setText("aun no has generado las llaves");
        }
    }//GEN-LAST:event_btn_descifrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_descifrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField textoCifrado;
    private javax.swing.JTextField textoDescifrado;
    // End of variables declaration//GEN-END:variables
}
