/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.rsatarea;
import java.math.BigInteger;
import java.util.Random;

/**
 *
 * @author Aaron
 */

public class GenerarLLaves extends javax.swing.JPanel {

    /**
     * Creates new form GenerarLLaves
     */
    
    int tamprimo; //2, 3, 4 etc
    BigInteger p, q, n;
    BigInteger fi;
    BigInteger e, d;
    
    //varibales que pasare
    public static BigInteger N,E,D;
    
    //constructor de RSA
    
    private GenerarLLaves(int tamprimo){
        this.tamprimo = tamprimo;
    }
    
    //metodo para generar los numeros primos
    private void generarPrimos(){
    
        p = new BigInteger(tamprimo, 10, new Random());
        
        do q = new BigInteger(tamprimo, 10, new Random());
         while(q.compareTo(p)==0); 
    
    }
    
    //generar la claves
    
    private void generarClaves(){
        /*
        Recordar que n = p*q
        fi = (p-1)*(q-1)
        */
        
        n = p.multiply(q);
        
        //(p-1)
        fi = p.subtract(BigInteger.valueOf(1));
        
        fi = fi.multiply(q.subtract(BigInteger.valueOf(1)));
        
        /*
        como calculabamos a e
        
        e debe de ser un coprimo de n de tal que
        1<e<fi(n)
        */
        
        do e = new BigInteger(2*tamprimo, new Random());
        while((e.compareTo(fi) != -1) || (e.gcd(fi).compareTo(BigInteger.valueOf(1)) != 0));
        
        //calcular a d = e ^ 1 mod fi   inverso multiplicativo de e
        
        d = e.modInverse(fi);
    
        
    }
    
    public GenerarLLaves() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        btn_generar = new javax.swing.JButton();
        label_p = new javax.swing.JLabel();
        label_n = new javax.swing.JLabel();
        label_q = new javax.swing.JLabel();
        tamañoPrimos = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setBackground(new java.awt.Color(204, 204, 0));

        btn_generar.setText("Generar");
        btn_generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generarActionPerformed(evt);
            }
        });

        label_p.setText("E:");

        label_n.setText("N:");

        label_q.setText("D:");

        tamañoPrimos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3" }));
        tamañoPrimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamañoPrimosActionPerformed(evt);
            }
        });

        jLabel4.setText("Escoje el tamaño de los numero primos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(btn_generar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_n, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_q, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_p, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tamañoPrimos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_p, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label_q, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(label_n, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tamañoPrimos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(btn_generar)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generarActionPerformed
        int tamprimo1;
        if (Integer.parseInt((String) tamañoPrimos.getSelectedItem()) == 2){
            tamprimo1 = 5;
        }else{
            tamprimo1 = 8;
        }
        
        GenerarLLaves rsa = new GenerarLLaves(tamprimo1);
        rsa.generarPrimos();
        rsa.generarClaves();
        
        N = rsa.n;
        E = rsa.e;
        D = rsa.d;
        
        label_n.setText("N:"+String.valueOf(N));
        label_p.setText("E:"+String.valueOf(E));
        label_q.setText("D:"+String.valueOf(D));
        
        System.out.println("P:"+rsa.p+"Q:"+rsa.q);
    }//GEN-LAST:event_btn_generarActionPerformed

    private void tamañoPrimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamañoPrimosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tamañoPrimosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_generar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel label_n;
    private javax.swing.JLabel label_p;
    private javax.swing.JLabel label_q;
    private javax.swing.JComboBox<String> tamañoPrimos;
    // End of variables declaration//GEN-END:variables
}
