/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.rsatarea;
/**
 *
 * @author Aaron
 */
public class InterfasRSA extends javax.swing.JFrame {

    /**
     * Creates new form InterfasRSA
     */
    
    Cifrar Cifrar = new Cifrar();
    Descifrar Descifrar = new Descifrar();
    GenerarLLaves GenerarLLaves = new GenerarLLaves();
    
    public InterfasRSA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        botones = new javax.swing.JPanel();
        btn_generar = new javax.swing.JButton();
        btn_cifrar = new javax.swing.JButton();
        btn_Descifrar = new javax.swing.JButton();
        btn_gato = new javax.swing.JButton();
        Gato = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contenedor.setLayout(new java.awt.BorderLayout());

        botones.setBackground(new java.awt.Color(204, 204, 255));

        btn_generar.setText("Generar llaves");
        btn_generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generarActionPerformed(evt);
            }
        });
        botones.add(btn_generar);

        btn_cifrar.setText("Cifrar");
        btn_cifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cifrarActionPerformed(evt);
            }
        });
        botones.add(btn_cifrar);

        btn_Descifrar.setText("Descifrar");
        btn_Descifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DescifrarActionPerformed(evt);
            }
        });
        botones.add(btn_Descifrar);

        btn_gato.setText("Gato");
        btn_gato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gatoActionPerformed(evt);
            }
        });
        botones.add(btn_gato);

        contenedor.add(botones, java.awt.BorderLayout.PAGE_END);

        Gato.setBackground(new java.awt.Color(255, 0, 153));
        Gato.setLayout(new java.awt.GridBagLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aaron\\Desktop\\,\\5IV7 SWyA Ugalde Tellez Aaron\\RSATarea\\src\\main\\java\\com\\mycompany\\rsatarea\\gato.jpg")); // NOI18N
        Gato.add(jLabel2, new java.awt.GridBagConstraints());

        contenedor.add(Gato, java.awt.BorderLayout.CENTER);

        getContentPane().add(contenedor, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cifrarActionPerformed
        contenedor.add(Cifrar);
        Cifrar.setVisible(true);
        Descifrar.setVisible(false);
        Gato.setVisible(false);
        GenerarLLaves.setVisible(false);
    }//GEN-LAST:event_btn_cifrarActionPerformed

    private void btn_DescifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DescifrarActionPerformed
        contenedor.add(Descifrar);
        Cifrar.setVisible(false);
        Descifrar.setVisible(true);
        Gato.setVisible(false);
        GenerarLLaves.setVisible(false);
    }//GEN-LAST:event_btn_DescifrarActionPerformed

    private void btn_gatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gatoActionPerformed
        Cifrar.setVisible(false);
        Descifrar.setVisible(false);
        Gato.setVisible(true);
        GenerarLLaves.setVisible(false);
    }//GEN-LAST:event_btn_gatoActionPerformed

    private void btn_generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generarActionPerformed
        contenedor.add(GenerarLLaves);
        Cifrar.setVisible(false);
        Descifrar.setVisible(false);
        Gato.setVisible(false);
        GenerarLLaves.setVisible(true);
    }//GEN-LAST:event_btn_generarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfasRSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfasRSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfasRSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfasRSA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new InterfasRSA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Gato;
    private javax.swing.JPanel botones;
    private javax.swing.JButton btn_Descifrar;
    private javax.swing.JButton btn_cifrar;
    private javax.swing.JButton btn_gato;
    private javax.swing.JButton btn_generar;
    private javax.swing.JPanel contenedor;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
